import Vue from 'vue'
import {Uploader,Tab, Tabs,Cell, CellGroup,Form,Field,Button,Toast,Swipe, SwipeItem,Search,NavBar,List,
    PullRefresh,Icon,GoodsAction, GoodsActionIcon, GoodsActionButton,Divider,Tabbar,TabbarItem,Popup,
    Card,Stepper,RadioGroup, Radio,SwipeCell    } from 'vant';
import 'vant/lib/uploader/style';
import 'vant/lib/cell/style';
import 'vant/lib/cell-group/style';
import 'vant/lib/form/style';
import 'vant/lib/field/style';
import 'vant/lib/button/style';
import 'vant/lib/toast/style';
import 'vant/lib/swipe/style';
import 'vant/lib/search/style';
import 'vant/lib/nav-bar/style';
import 'vant/lib/list/style';
import 'vant/lib/pull-refresh/style';
import 'vant/lib/goods-action/style';
import 'vant/lib/goods-action-icon/style';
import 'vant/lib/goods-action-button/style';
import 'vant/lib/tabbar/style';
import 'vant/lib/tabbar-item/style';
import 'vant/lib/tab/style';
import 'vant/lib/tabs/style';
import 'vant/lib/card/style';
import 'vant/lib/stepper/style';
import 'vant/lib/radio-group/style';
import 'vant/lib/radio/style';
import 'vant/lib/swipe-cell/style';

Vue.use(Uploader);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Form);
Vue.use(Field);
Vue.use(Button);
Vue.use(Toast);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Search);
Vue.use(NavBar);
Vue.use(List);
Vue.use(PullRefresh);
Vue.use(Icon);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
Vue.use(Divider);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Popup);
Vue.use(Card);
Vue.use(Stepper);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(SwipeCell);